### ISSUE TITLE
broken pipeline due to processing 

### ISSUE THREAD

**Issue by naarkhoo** [jasn/regnskaber#4]
Each time I run the fetch.py after a while (Randomly) I encounter the following error, 

```
BrokenPipeError: [Errno 32] Broken pipe
Process Process-1278:
Traceback (most recent call last):
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/Virk/lib/python3.6/site-packages/regnskaber/fetch.py", line 206, in consumer_insert
  File "<string>", line 2, in size
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process Process-1279:
Traceback (most recent call last):
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/Virk/lib/python3.6/site-packages/regnskaber/fetch.py", line 206, in consumer_insert
  File "<string>", line 2, in size
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/anaconda3/envs/Virk/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

which I guess points to 

```
        try:
            queue_lock.acquire()

            if queue.size() == 0:
                do_sleep = True
                continue
            msg = queue.get()
            popped, pushed = queue.get_statistics()
            print(ERASE + 'Inserting into db: %s/%s' % (popped, pushed),
                  end='', flush=True)
        finally:
            queue_lock.release()
            if do_sleep:
                time.sleep(4)
```

I appreciate if you help me to diagnose and fix this issue.

**Comment by jasn** [comment]
I don't maintain this anymore since I don't use it myself. I think you can find an active fork here: https://github.com/gronlund/regnskaber.

Here is where I would look if I were you:
Looks like it's a broken pipe, so it's probably because for some reason the IOQueueManager's process has shut down.
